tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "FelixKratz/formulae"

brew "fnm"
brew "fzf"
brew "git"
brew "starship"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "borders"

cask "alacritty"
cask "font-fira-code-nerd-font"
