#!/usr/bin/env sh

yabai -m config window_shadow                float
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   05

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^システム環境設定$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^ディスクユーティリティ$" manage=off
yabai -m rule --add app="^アーカイブユーティリティ$" manage=off
yabai -m rule --add app="^システム情報$" manage=off
yabai -m rule --add app="^アクティビティモニタ$" manage=off
yabai -m rule --add app="^ブック$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add title="のインストール$" manage=off
yabai -m rule --add title=" を開く$" manage=off

# Set the border color for active and inactive windows
borders active_color=0xff40ff00 width=5.0 &

echo "yabai configuration loaded.."
